package com.ticketmafia.shared;

// Sprint: v1 | Feature: FR-001..FR-012,NFR-003,NFR-004 | US: US-001..US-012 | Task Group: TG 1.1..TG 1.6
// Contract: coding-standards-backend.md Error Code Catalog; api-specs-v1.md API-001..API-015/API-016
public enum ErrorCode {
    AUTH_IDENTIFIER_INVALID,
    AUTH_CHALLENGE_INVALID,
    AUTH_UNAUTHORIZED,
    AUTH_OTP_INVALID,
    AUTH_FORBIDDEN,
    AUTH_CHALLENGE_NOT_FOUND,
    AUTH_CHALLENGE_USED,
    ADMIN_MATCH_INVALID_REQUEST,
    ADMIN_FORBIDDEN,
    MATCH_NOT_FOUND,
    MATCH_DUPLICATE,
    MATCH_NOT_OPEN_FOR_SALE,
    MATCH_QUERY_INVALID,
    MATCH_NOT_SELLABLE,
    SEAT_QUERY_INVALID,
    SEAT_UNAVAILABLE,
    SEAT_GENERATE_INVALID_REQUEST,
    SEATS_ALREADY_EXIST,
    PRICE_INVALID_REQUEST,
    MATCH_PRICE_LOCKED,
    QR_CONFIG_INVALID_REQUEST,
    CHECKOUT_INVALID_REQUEST,
    CHECKOUT_RESOURCE_NOT_FOUND,
    CHECKOUT_LIMIT_EXCEEDED,
    ORDER_NOT_FOUND,
    ORDER_FORBIDDEN,
    ORDER_NOT_HELD,
    ORDER_NOT_PENDING_CONFIRM,
    PAYMENT_COMPLETION_INVALID_REQUEST,
    ADMIN_DECISION_INVALID_REQUEST,
    ORDER_QUERY_INVALID,
    TICKET_INVALID_REQUEST,
    TICKET_FORBIDDEN,
    TICKET_NOT_FOUND,
    TICKET_NOT_VALID_FOR_QR,
    SCAN_TOKEN_INVALID,
    SCAN_FORBIDDEN,
    TICKET_ALREADY_SCANNED,
    EXCHANGE_INVALID_REQUEST,
    TICKET_OR_SEAT_NOT_FOUND,
    EXCHANGE_STATE_CONFLICT,
    EXCHANGE_CHEAPER_SEAT_NOT_ALLOWED,
    EXCHANGE_DECISION_INVALID_REQUEST,
    EXCHANGE_NOT_PENDING_CONFIRM,
    RATE_LIMITED,
    VALIDATION_ERROR,
    INTERNAL_ERROR;

    public String code() {
        return name();
    }
}
