*** Settings ***
Resource    ../../KeywordLibraries/RealEstateOps/VerificationKeywords/VerificationKeywords_Login.resource
Resource    ../../KeywordLibraries/RealEstateOps/HighLevelKeywords/HighLevelKeywords_Login.resource
Resource    ../../KeywordLibraries/RealEstateOps/HighLevelKeywords/HighLevelKeywords_QuanLyNhanVien.resource
Resource    ../../KeywordLibraries/RealEstateOps/VerificationKeywords/VerificationKeywords_QuanLyNhanVien.resource
Resource    ../../KeywordLibraries/RealEstateOps/LowLevelKeywords/NSP_UI_Utils.resource
Resource    ../../KeywordLibraries/RealEstateOps/HighLevelKeywords/HighLevelKeywords_Menu.resource